- name: "Install epel"
  become: true
  ansible.builtin.yum:
    name:
      - epel-release
    update_cache: true

- name: "Inatall dependencies"
  become: true
  ansible.builtin.yum:
    name:
      - "@Development Tools"
      - libxml2-devel
      - libxslt-devel
      - libpqxx-devel

- name: "Copy xpaste app"
  ansible.builtin.copy:
    src: xpaste_practicum/
    dest: ~/xpaste_practicum

- name: "Build app"
  shell:
    bundle config build.nokogiri --use-system-libraries
    bundle install --clean --no-cache --without development
  args:
    chdir: ~/xpaste_practicum

- name: "Bundle install"
  shell:
    bundle install
  args:
    chdir: ~/xpaste_practicum
  ignore_errors: true
